# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zxyz_database
    username: root
    password: 123456
  servlet:
    multipart:
      # 最大文件大小
      max-file-size: 1GB
      # 最大请求大小(多个文件)(包含文件和表单数据)
      max-request-size: 1GB
  # MyBatis 配置
  # 开启驼峰命名映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  # 阿里云OSS配置
  #oss.endpoint=oss-cn-beijing.aliyuncs.com
oss:
  region: cn-shenzhen
  bucket: zxyz-database
server:
  port: 8080